exclude_patterns:
- "tests/"
- "build/"
- "coverage/"
- "tests/"
- "dist/"
- "docs/"
- "node_modules/"
- "."
- "Gruntfile.js"
- "*.md"
- "LICENSE"
- "package*"
plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc
  git-legal:
    enabled: true


